import type { McpToolDefinition, UpstreamInfo } from "./types.js";

/** Emits a production proposer bridge with Tasks-first MCP protocol detection. */
export function generateBridge(info: UpstreamInfo): string {
  const upstream = [info.command, ...info.args].join(" ");
  const serverName = `${info.serverName}-mpas-bridge`;
  const serverVersion = info.serverVersion ?? "1.0.0";

  return `#!/usr/bin/env node
/**
 * MPAS Bridge MCP Server
 * Generated by bridge-generator
 * Upstream: ${escapeComment(upstream)}
 *
 * This file is generated then checked in. Edit freely.
 *
 * Uses MCP 2026-07-28 Tasks when supported and the legacy MPAS wait-tool
 * compatibility surface for conventional MCP clients.
 */

import { readFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { StdioServerTransport } from "@modelcontextprotocol/server/stdio";
import {
  ActionPackageBuilder,
  ActionEndpointClient,
  ActionRelayClient,
  buildDeliveryEnvelope,
  CoordinationServiceClient,
  KeyManager,
  MemoryWorkflowStore,
  MpasProtocolServer,
  ProposerBridge,
} from "@oma3/mpas";
import type {
  BridgeUpstreamTool,
  ActionRequest,
  Did,
  MpasApplicationPlugin,
  ProposerConfig,
  WorkflowCoordinationService,
  WorkflowActionEndpoint,
  WorkflowStore,
} from "@oma3/mpas";
import { SqliteWorkflowStore } from "./sqlite-workflow-store.js";

const TOOLS = loadTools();

interface WorkflowConfig {
  /** SQLite database path. Omitted → in-memory store (no restart durability). */
  dbPath?: string;
  /** Minimum post-resolution retention disclosed to clients. Default 86400. */
  resultRetentionSeconds?: number;
  /** Background tick interval. Default 2000ms. */
  pollIntervalMs?: number;
  /** Client-facing tasks/get polling hint. Default 5000ms. */
  taskPollIntervalMs?: number;
  /** Compatibility wait-tool maximum. Default 300 seconds. */
  maxWaitTimeoutSeconds?: number;
  /** Deployment assigns maintainer notification outside the proposing client. */
  notificationAssignedElsewhere?: boolean;
  /**
   * Action and Coordination HTTP wait. Must stay below claimLeaseMs.
   * Default 30000.
   */
  submissionTimeoutMs?: number;
  /** Worker claim lease. Must exceed submissionTimeoutMs. Default 60000. */
  claimLeaseMs?: number;
}

interface BridgeConfig extends Omit<ProposerConfig, "approvalStrategy" | "approvalTimeoutMs"> {
  actionEndpoint?: RelayActionEndpointConfig;
  workflow?: WorkflowConfig;
}

interface RelayActionEndpointConfig {
  url: string;
  verifierDid: Did;
  additionalRecipients?: Did[];
}

interface CliConfig {
  mode?: "proposer" | "maintainer";
  plugin?: string;
  adapter?: {
    url?: string;
  };
  actionEndpoint?: {
    url?: string;
    verifierDid?: string;
    additionalRecipients?: string[];
  };
  coordination?: {
    url?: string;
  };
  agent?: {
    did?: string;
    keyFile?: string;
  };
  target?: {
    applicationDid?: string;
  };
  applicationDid?: string;
  adapterUrl?: string;
  agentKey?: string;
  executionProfile?: {
    id: string;
    format: string;
  };
  workflow?: WorkflowConfig;
  defaultExpirationMinutes?: number;
  /** @deprecated Official MCP Tasks are always used. */
  approvalStrategy?: string;
  /** @deprecated See approvalStrategy. */
  approvalTimeoutMs?: number;
}

function log(level: "info" | "warn" | "error", msg: string, data?: object): void {
  const entry = { ts: new Date().toISOString(), level, msg, ...data };
  process.stderr.write(\`[mpas-bridge] \${JSON.stringify(entry)}\\n\`);
}

export class GeneratedBridge {
  private readonly bridgePromise: Promise<ProposerBridge>;
  private readonly store: WorkflowStore;

  constructor(config: BridgeConfig) {
    const plugin = loadPlugin(config.plugin);
    const keyManagerPromise = loadKeyManager(config.agentKey);
    const workflow = config.workflow ?? {};
    const submissionTimeoutMs = workflow.submissionTimeoutMs;
    const actionEndpoint: WorkflowActionEndpoint = config.actionEndpoint
      ? relayActionEndpoint(config.actionEndpoint, keyManagerPromise, submissionTimeoutMs)
      : new ActionEndpointClient({
          url: config.adapterUrl,
          signer: keyManagerPromise,
          ...(submissionTimeoutMs !== undefined ? { timeoutMs: submissionTimeoutMs } : {}),
        });
    const coordinationService: WorkflowCoordinationService = config.coordinationUrl
      ? new CoordinationServiceClient({
          url: config.coordinationUrl,
          signer: keyManagerPromise,
          ...(submissionTimeoutMs !== undefined ? { timeoutMs: submissionTimeoutMs } : {}),
        })
      : unconfiguredCoordinationService();
    this.store = workflow.dbPath ? new SqliteWorkflowStore(workflow.dbPath) : new MemoryWorkflowStore();
    if (!workflow.dbPath) {
      log("warn", "memory_workflow_store", {
        note: "No workflow.dbPath configured; active Actions will not survive a bridge restart.",
      });
    }

    this.bridgePromise = keyManagerPromise.then((keyManager) => {
      const executionProfile = config.executionProfile ?? {
        id: plugin.executionProfile.id,
        format: plugin.executionProfile.format ?? "mcp.toolsCall",
      };
      const actionPackageBuilder = new ActionPackageBuilder({
        applicationDid: config.applicationDid,
        executionProfile,
        signer: keyManager,
        ...(config.defaultExpirationMinutes !== undefined
          ? { defaultExpirationMinutes: config.defaultExpirationMinutes }
          : {}),
      });
      return new ProposerBridge({
        tools: [...TOOLS],
        buildActionPackage: (toolName, args) => actionPackageBuilder.buildFromToolCall(toolName, args),
        buildCoordinationReplacement: (priorPackage, verifierRequirements) =>
          actionPackageBuilder.buildCoordinationReplacement(priorPackage, verifierRequirements),
        store: this.store,
        actionEndpoint,
        coordinationService,
        proposerDid: keyManager.did,
        resultRetentionSeconds: workflow.resultRetentionSeconds ?? 86_400,
        ...(workflow.pollIntervalMs !== undefined ? { pollIntervalMs: workflow.pollIntervalMs } : {}),
        ...(workflow.taskPollIntervalMs !== undefined ? { taskPollIntervalMs: workflow.taskPollIntervalMs } : {}),
        ...(workflow.maxWaitTimeoutSeconds !== undefined ? { maxWaitTimeoutSeconds: workflow.maxWaitTimeoutSeconds } : {}),
        ...(workflow.notificationAssignedElsewhere !== undefined
          ? { notificationAssignedElsewhere: workflow.notificationAssignedElsewhere }
          : {}),
        ...(submissionTimeoutMs !== undefined ? { submissionTimeoutMs } : {}),
        ...(workflow.claimLeaseMs !== undefined ? { claimLeaseMs: workflow.claimLeaseMs } : {}),
      });
    });
  }

  getToolDefinitions(): BridgeUpstreamTool[] {
    return structuredClone(TOOLS);
  }

  async handleToolCall(
    toolName: string,
    args: object,
  ): Promise<Awaited<ReturnType<ProposerBridge["handleToolCall"]>>> {
    log("info", "tool_call_received", { toolName });
    const bridge = await this.bridgePromise;
    return bridge.handleToolCall(toolName, args);
  }

  /** Startup reconciliation plus the background workflow loop. */
  async start(): Promise<void> {
    const bridge = await this.bridgePromise;
    await bridge.start();
    log("info", "bridge_started");
  }

  stop(): void {
    void this.bridgePromise.then((bridge) => {
      bridge.stop();
      this.store.close();
    });
  }

  async buildMcpServer(): Promise<MpasProtocolServer> {
    return new MpasProtocolServer({
      bridge: await this.bridgePromise,
      serverInfo: {
        name: ${JSON.stringify(serverName)},
        version: ${JSON.stringify(serverVersion)},
      },
      onerror(error) {
        log("error", "mcp_protocol_error", { message: error.message });
      },
      onmode(mode, selector) {
        log("info", "mcp_protocol_mode_selected", { mode, selector });
      },
    });
  }
}

/**
 * Placeholder used when no coordinationUrl is configured. Approval-gated
 * Actions stay durably recorded in created/awaitingApprovals and are retried
 * by reconciliation; they cannot complete until coordination exists.
 */
function unconfiguredCoordinationService(): WorkflowCoordinationService {
  return {
    createApprovalWorkflow() {
      return Promise.reject(new Error("Coordination Service is not configured (coordination.url)."));
    },
    pollWork() {
      return Promise.resolve({
        version: "1" as const,
        type: "CoordinationPollResponse" as const,
        approvalRequests: [],
        actionUpdates: [],
      });
    },
    cancelAction() {
      return Promise.reject(new Error("Coordination Service is not configured (coordination.url)."));
    },
  };
}

function relayActionEndpoint(
  config: RelayActionEndpointConfig,
  keyManagerPromise: Promise<KeyManager>,
  timeoutMs: number | undefined,
): WorkflowActionEndpoint {
  const client = new ActionRelayClient({
    url: config.url,
    signer: keyManagerPromise,
    ...(timeoutMs !== undefined ? { timeoutMs } : {}),
  });
  const recipients = [...new Set([config.verifierDid, ...(config.additionalRecipients ?? [])])];
  return {
    async submitActionRequest(request: ActionRequest) {
      const keyManager = await keyManagerPromise;
      return client.submitAction(buildDeliveryEnvelope({
        sender: keyManager.did,
        recipients,
        payload: request,
      }));
    },
  };
}

export async function createBridgeFromConfig(configPath: string): Promise<GeneratedBridge> {
  const absoluteConfigPath = resolve(configPath);
  const configDir = dirname(absoluteConfigPath);
  const config = JSON.parse(await readFile(absoluteConfigPath, "utf8")) as CliConfig;
  return new GeneratedBridge(toBridgeConfig(config, configDir));
}

export async function runBridge(argv = process.argv.slice(2)): Promise<void> {
  const configPath = configPathFromArgs(argv);
  const bridge = await createBridgeFromConfig(configPath);
  const server = await bridge.buildMcpServer();
  const transport = new StdioServerTransport();

  await bridge.start();
  await server.connect(transport);
}

function toBridgeConfig(config: CliConfig, configDir: string): BridgeConfig {
  if (config.mode === "maintainer") {
    throw new Error("Maintainer/signer mode is not supported by this proposer bridge.");
  }
  if (!config.plugin) {
    throw new Error('Proposer bridge config requires "plugin".');
  }
  if (config.approvalStrategy !== undefined || config.approvalTimeoutMs !== undefined) {
    log("warn", "deprecated_config_ignored", {
      note: "approvalStrategy/approvalTimeoutMs are ignored: the bridge uses asynchronous Tasks or compatibility results.",
    });
  }
  const pluginPath = resolve(configDir, config.plugin);
  const plugin = loadPlugin(pluginPath);
  const adapterUrl = config.adapter?.url ?? config.adapterUrl;
  const actionEndpointUrl = config.actionEndpoint?.url;
  const verifierDid = config.actionEndpoint?.verifierDid;
  const agentKey = config.agent?.keyFile ?? config.agentKey;
  if (!adapterUrl && !actionEndpointUrl) {
    throw new Error('Proposer bridge config requires either "actionEndpoint.url" or "adapter.url".');
  }
  if (actionEndpointUrl && !verifierDid) {
    throw new Error('Relay action endpoint config requires "actionEndpoint.verifierDid".');
  }
  if (!agentKey) {
    throw new Error('Proposer bridge config requires "agent.keyFile".');
  }

  const workflow: WorkflowConfig = { ...config.workflow };
  if (workflow.dbPath) {
    workflow.dbPath = resolve(configDir, workflow.dbPath);
  }

  return {
    plugin: pluginPath,
    applicationDid: (config.target?.applicationDid ?? config.applicationDid ?? plugin.applicationDid) as BridgeConfig["applicationDid"],
    adapterUrl: adapterUrl ?? actionEndpointUrl!,
    ...(actionEndpointUrl && verifierDid
      ? {
          actionEndpoint: {
            url: actionEndpointUrl,
            verifierDid: verifierDid as Did,
            additionalRecipients: (config.actionEndpoint?.additionalRecipients ?? []) as Did[],
          },
        }
      : {}),
    agentKey: resolve(configDir, agentKey),
    coordinationUrl: config.coordination?.url,
    executionProfile: (config.executionProfile ?? {
      id: plugin.executionProfile.id,
      format: plugin.executionProfile.format ?? "mcp.toolsCall",
    }) as BridgeConfig["executionProfile"],
    defaultExpirationMinutes: config.defaultExpirationMinutes,
    workflow,
  };
}

function loadTools(): BridgeUpstreamTool[] {
  const raw = readFileSync(new URL("./tools.json", import.meta.url), "utf8");
  return JSON.parse(raw) as BridgeUpstreamTool[];
}

function loadPlugin(plugin: BridgeConfig["plugin"]): MpasApplicationPlugin {
  if (typeof plugin === "string") {
    return JSON.parse(readFileSync(plugin, "utf8")) as MpasApplicationPlugin;
  }

  return plugin;
}

function loadKeyManager(agentKey: BridgeConfig["agentKey"]): Promise<KeyManager> {
  if (typeof agentKey === "string") {
    return KeyManager.fromFile(agentKey);
  }

  return Promise.resolve(KeyManager.fromJwk(agentKey));
}

function configPathFromArgs(argv: string[]): string {
  const configIndex = argv.indexOf("--config");
  const configPath = configIndex >= 0 ? argv[configIndex + 1] : undefined;
  if (!configPath) {
    throw new Error("Usage: mpas-bridge --config <path>");
  }

  return configPath;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await runBridge();
}
`;
}

export function generateToolsJson(tools: McpToolDefinition[]): string {
  return `${JSON.stringify(tools, null, 2)}\n`;
}
/**
 * Emits the SQLite workflow store as standalone repository code next to the
 * bridge. The SDK ships only the WorkflowStore contract and an in-memory
 * reference; durable persistence is deployment code, and this file is the
 * reference implementation. Keep in sync with
 * examples/demo/src/bridge/sqlite-workflow-store.ts.
 */
export function generateWorkflowStore(): string {
  return `import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { DatabaseSync } from "node:sqlite";
import type {
  BridgeWorkflowState,
  CreateWorkflowInput,
  ReplaceWorkflowActionInput,
  WorkflowRecord,
  WorkflowResolution,
  WorkflowStore,
} from "@oma3/mpas";

/**
 * SQLite reference implementation of the SDK's WorkflowStore contract
 * (implementation plan §5.3). This is OMA3's durable store for the GitHub
 * bridge deployment; it lives in the repository rather than the SDK because
 * the MCP Tasks integration does not require any particular persistence mechanism.
 *
 * - one configured database path per bridge deployment;
 * - transactional workflow transitions (single-statement check-and-write);
 * - WAL mode so a persistent worker can share the file with a thin frontend;
 * - schema versioning with fail-safe open;
 * - no credentials or adapter secrets stored.
 */

const SCHEMA_VERSION = 3;

const TERMINAL_STATES: ReadonlySet<BridgeWorkflowState> = new Set(["resolved", "unresolvable", "cancelled"]);

export class SqliteWorkflowStore implements WorkflowStore {
  private readonly db: DatabaseSync;
  private readonly now: () => number;

  constructor(path: string, options: { now?: () => number } = {}) {
    this.now = options.now ?? (() => Date.now());
    if (path !== ":memory:") {
      mkdirSync(dirname(path), { recursive: true });
    }
    this.db = new DatabaseSync(path);
    this.db.exec("PRAGMA journal_mode = WAL");
    this.db.exec("PRAGMA busy_timeout = 5000");
    this.migrate();
  }

  close(): void {
    this.db.close();
  }

  createWorkflow(input: CreateWorkflowInput): WorkflowRecord {
    if (input.taskId === input.actionId) {
      throw new Error("Task ID and Action ID must be distinct.");
    }
    const at = this.timestamp();
    try {
      this.db.exec("BEGIN IMMEDIATE");
      this.db
        .prepare(
          \`INSERT INTO workflows (
             action_id, current_action_id, action_idempotency_key, envelope_hash, tool_name, state, action_package,
             adapter_attempts, expires_at, created_at, updated_at
           ) VALUES (?, ?, ?, ?, ?, 'created', ?, '[]', ?, ?, ?)\`,
        )
        .run(
          input.taskId,
          input.actionId,
          input.actionIdempotencyKey,
          input.actionEnvelopeHash,
          input.toolName,
          toJson(input.actionPackage),
          input.expiresAt,
          at,
          at,
        );
      this.db
        .prepare("INSERT INTO workflow_action_aliases (action_id, task_id) VALUES (?, ?)")
        .run(input.actionId, input.taskId);
      this.db.exec("COMMIT");
    } catch (error) {
      rollback(this.db);
      if (isUniqueViolation(error)) {
        throw new Error(\`Workflow already exists for task \${input.taskId} or action \${input.actionId}.\`);
      }
      throw error;
    }
    return this.mustGet(input.taskId);
  }

  getWorkflow(taskId: string): WorkflowRecord | undefined {
    const row = this.db.prepare("SELECT * FROM workflows WHERE action_id = ?").get(taskId) as
      | Record<string, unknown>
      | undefined;
    return row ? rowToRecord(row) : undefined;
  }

  getWorkflowByActionId(actionId: string): WorkflowRecord | undefined {
    const row = this.db
      .prepare(
        \`SELECT workflows.*
           FROM workflow_action_aliases
           JOIN workflows ON workflows.action_id = workflow_action_aliases.task_id
          WHERE workflow_action_aliases.action_id = ?\`,
      )
      .get(actionId) as Record<string, unknown> | undefined;
    return row ? rowToRecord(row) : undefined;
  }

  replaceAction(taskId: string, input: ReplaceWorkflowActionInput): WorkflowRecord {
    if (taskId === input.actionId) {
      throw new Error("Task ID and Action ID must be distinct.");
    }
    try {
      this.db.exec("BEGIN IMMEDIATE");
      this.db
        .prepare("INSERT INTO workflow_action_aliases (action_id, task_id) VALUES (?, ?)")
        .run(input.actionId, taskId);
      const result = this.db
        .prepare(
          \`UPDATE workflows
              SET current_action_id = ?, action_idempotency_key = ?, envelope_hash = ?, action_package = ?,
                  authorization_requirements = ?, coordination_ref = NULL,
                  completed_package = NULL, expires_at = ?,
                  state = 'submittingToCoordination', updated_at = ?
            WHERE action_id = ? AND state = ?\`,
        )
        .run(
          input.actionId,
          input.actionIdempotencyKey,
          input.actionEnvelopeHash,
          toJson(input.actionPackage),
          toJson(input.authorizationRequirements),
          input.expiresAt,
          this.timestamp(),
          taskId,
          input.fromState,
        );
      if (result.changes !== 1) {
        throw new Error(\`Workflow \${taskId} is not in replacement state \${input.fromState}.\`);
      }
      this.db.exec("COMMIT");
    } catch (error) {
      rollback(this.db);
      throw error;
    }
    return this.mustGet(taskId);
  }

  compareAndSetState(taskId: string, from: BridgeWorkflowState, to: BridgeWorkflowState): boolean {
    if (TERMINAL_STATES.has(from) || TERMINAL_STATES.has(to)) {
      return false;
    }
    const result = this.db
      .prepare("UPDATE workflows SET state = ?, updated_at = ? WHERE action_id = ? AND state = ?")
      .run(to, this.timestamp(), taskId, from);
    return result.changes === 1;
  }

  claimWorkflow(taskId: string, workerId: string, leaseMs: number): boolean {
    const nowMs = this.now();
    const result = this.db
      .prepare(
        \`UPDATE workflows
           SET claimed_by = ?, claim_expires_ms = ?, updated_at = ?
         WHERE action_id = ?
           AND state NOT IN ('resolved', 'unresolvable', 'cancelled')
           AND (claimed_by IS NULL OR claimed_by = ? OR claim_expires_ms <= ?)\`,
      )
      .run(workerId, nowMs + leaseMs, this.timestamp(), taskId, workerId, nowMs);
    return result.changes === 1;
  }

  saveCoordinationReference(taskId: string, ref: unknown): void {
    this.setColumn(taskId, "coordination_ref", toJson(ref));
  }

  saveCompletedPackage(taskId: string, completedPackage: unknown): void {
    this.setColumn(taskId, "completed_package", toJson(completedPackage));
  }

  saveAuthorizationRequirements(taskId: string, requirements: unknown): void {
    this.setColumn(taskId, "authorization_requirements", toJson(requirements));
  }

  saveLastActionResponse(taskId: string, response: unknown): void {
    this.setColumn(taskId, "last_action_response", toJson(response));
  }

  saveAdapterAttempt(taskId: string, attempt: unknown): void {
    this.db
      .prepare(
        \`UPDATE workflows
           SET adapter_attempts = json_insert(adapter_attempts, '$[#]', json(?)), updated_at = ?
         WHERE action_id = ?\`,
      )
      .run(toJson(attempt), this.timestamp(), taskId);
  }

  resolveWorkflow(taskId: string, resolution: WorkflowResolution): void {
    const state: BridgeWorkflowState = resolution.kind;
    const at = this.timestamp();
    this.db
      .prepare(
        \`UPDATE workflows
           SET state = ?, resolution = ?, resolved_at = ?, updated_at = ?
         WHERE action_id = ?
           AND state NOT IN ('resolved', 'unresolvable', 'cancelled')\`,
      )
      .run(state, toJson(resolution), at, at, taskId);
  }

  cancelWorkflow(taskId: string): boolean {
    const at = this.timestamp();
    const resolution: WorkflowResolution = { kind: "cancelled", cancelledAt: at };
    const result = this.db
      .prepare(
        \`UPDATE workflows
           SET state = 'cancelled', resolution = ?, resolved_at = ?, updated_at = ?
         WHERE action_id = ?
           AND state NOT IN ('resolved', 'unresolvable', 'cancelled')\`,
      )
      .run(toJson(resolution), at, at, taskId);
    return result.changes === 1;
  }

  listRecoverableWorkflows(): WorkflowRecord[] {
    const rows = this.db
      .prepare("SELECT * FROM workflows WHERE state NOT IN ('resolved', 'unresolvable', 'cancelled') ORDER BY created_at")
      .all() as Record<string, unknown>[];
    return rows.map(rowToRecord);
  }

  purgeExpiredResults(retentionMs: number = 24 * 60 * 60 * 1000): number {
    const rows = this.db
      .prepare("SELECT action_id AS task_id, expires_at, resolved_at FROM workflows WHERE state IN ('resolved', 'unresolvable', 'cancelled')")
      .all() as { task_id: string; expires_at: string; resolved_at: string }[];

    const nowMs = this.now();
    let purged = 0;
    for (const row of rows) {
      const keepUntil = Math.max(Date.parse(row.expires_at), Date.parse(row.resolved_at) + retentionMs);
      if (nowMs > keepUntil) {
        this.db.prepare("DELETE FROM workflow_action_aliases WHERE task_id = ?").run(row.task_id);
        purged += this.db.prepare("DELETE FROM workflows WHERE action_id = ?").run(row.task_id).changes as number;
      }
    }
    return purged;
  }

  private setColumn(
    taskId: string,
    column: "coordination_ref" | "completed_package" | "authorization_requirements" | "last_action_response",
    json: string,
  ): void {
    this.db
      .prepare(\`UPDATE workflows SET \${column} = ?, updated_at = ? WHERE action_id = ?\`)
      .run(json, this.timestamp(), taskId);
  }

  private mustGet(taskId: string): WorkflowRecord {
    const record = this.getWorkflow(taskId);
    if (!record) {
      throw new Error(\`Workflow not found for task \${taskId}.\`);
    }
    return record;
  }

  private timestamp(): string {
    return new Date(this.now()).toISOString();
  }

  private migrate(): void {
    let { user_version: version } = this.db.prepare("PRAGMA user_version").get() as { user_version: number };
    if (version > SCHEMA_VERSION) {
      this.db.close();
      throw new Error(
        \`Workflow store schema version \${version} is newer than supported version \${SCHEMA_VERSION}; refusing to open.\`,
      );
    }
    if (version === SCHEMA_VERSION) {
      return;
    }

    // Legacy schemas (v1, v2) stored action_id as both the Task ID and
    // Action ID, which is incompatible with the current model where they
    // must be distinct. Synthesizing Task IDs for existing rows would
    // create aliases that conflict with the new uniqueness constraints.
    //
    // This migration assumes no outstanding legacy workflows require
    // preservation. If active workflows exist, the store refuses to start
    // unless explicitly overridden via MPAS_ALLOW_LEGACY_WORKFLOW_RESET=1.
    // Operators should cancel affected Coordination workflows first.
    if (version >= 1 && version < SCHEMA_VERSION) {
      const row = this.db.prepare("SELECT COUNT(*) AS cnt FROM workflows").get() as { cnt: number };
      if (row.cnt > 0) {
        // v1 has only action_id; v2 added current_action_id. Query the
        // columns that exist in every legacy schema.
        const active = this.db.prepare(
          "SELECT action_id FROM workflows WHERE state NOT IN ('resolved', 'unresolvable', 'cancelled')",
        ).all() as { action_id: string }[];
        if (active.length > 0 && !process.env.MPAS_ALLOW_LEGACY_WORKFLOW_RESET) {
          const ids = active.map((r) => r.action_id).join(", ");
          this.db.close();
          throw new Error(
            \`Legacy workflow store (schema v\${version}) contains \${active.length} active workflow(s) that will be discarded: \${ids}. \` +
            "Cancel them via the Coordination Service before upgrading, or set MPAS_ALLOW_LEGACY_WORKFLOW_RESET=1 to accept the loss.",
          );
        }
      }
      this.db.exec(\`
        BEGIN IMMEDIATE;
        DROP TABLE IF EXISTS workflow_action_aliases;
        DROP TABLE IF EXISTS workflows;
        COMMIT;
      \`);
      version = 0;
    }

    this.db.exec(\`
      CREATE TABLE IF NOT EXISTS workflows (
        action_id                  TEXT PRIMARY KEY,
        current_action_id          TEXT NOT NULL,
        action_idempotency_key     TEXT NOT NULL,
        envelope_hash              TEXT NOT NULL,
        tool_name                  TEXT NOT NULL,
        state                      TEXT NOT NULL,
        action_package             TEXT NOT NULL,
        authorization_requirements TEXT,
        coordination_ref           TEXT,
        completed_package          TEXT,
        adapter_attempts           TEXT NOT NULL DEFAULT '[]',
        last_action_response       TEXT,
        expires_at                 TEXT NOT NULL,
        created_at                 TEXT NOT NULL,
        updated_at                 TEXT NOT NULL,
        claimed_by                 TEXT,
        claim_expires_ms           INTEGER,
        resolved_at                TEXT,
        resolution                 TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_workflows_state ON workflows (state);
      CREATE UNIQUE INDEX IF NOT EXISTS idx_workflows_current_action_id
        ON workflows (current_action_id);
      CREATE TABLE IF NOT EXISTS workflow_action_aliases (
        action_id TEXT PRIMARY KEY,
        task_id   TEXT NOT NULL REFERENCES workflows(action_id)
      );
      CREATE INDEX IF NOT EXISTS idx_workflow_action_aliases_task ON workflow_action_aliases (task_id);
    \`);
    this.db.exec(\`PRAGMA user_version = \${SCHEMA_VERSION}\`);
  }
}

function toJson(value: unknown): string {
  return JSON.stringify(value ?? null);
}

function fromJson(value: unknown): unknown {
  if (value === null || value === undefined) {
    return undefined;
  }
  return JSON.parse(String(value));
}

function rowToRecord(row: Record<string, unknown>): WorkflowRecord {
  const record: WorkflowRecord = {
    taskId: String(row.action_id),
    actionId: String(row.current_action_id),
    actionIdempotencyKey: String(row.action_idempotency_key),
    actionEnvelopeHash: String(row.envelope_hash),
    toolName: String(row.tool_name),
    state: String(row.state) as BridgeWorkflowState,
    actionPackage: fromJson(row.action_package),
    adapterAttempts: (fromJson(row.adapter_attempts) as unknown[]) ?? [],
    expiresAt: String(row.expires_at),
    createdAt: String(row.created_at),
    updatedAt: String(row.updated_at),
  };

  const authorizationRequirements = fromJson(row.authorization_requirements);
  if (authorizationRequirements !== undefined) record.authorizationRequirements = authorizationRequirements;
  const coordinationRef = fromJson(row.coordination_ref);
  if (coordinationRef !== undefined) record.coordinationRef = coordinationRef;
  const completedPackage = fromJson(row.completed_package);
  if (completedPackage !== undefined) record.completedPackage = completedPackage;
  const lastActionResponse = fromJson(row.last_action_response);
  if (lastActionResponse !== undefined) record.lastActionResponse = lastActionResponse;
  if (row.claimed_by != null) record.claimedBy = String(row.claimed_by);
  if (row.claim_expires_ms != null) record.claimExpiresAt = new Date(Number(row.claim_expires_ms)).toISOString();
  if (row.resolved_at != null) record.resolvedAt = String(row.resolved_at);
  const resolution = fromJson(row.resolution);
  if (resolution !== undefined) record.resolution = resolution as WorkflowResolution;

  return record;
}

function rollback(db: DatabaseSync): void {
  try {
    db.exec("ROLLBACK");
  } catch {
    // No active transaction.
  }
}

function isUniqueViolation(error: unknown): boolean {
  return error instanceof Error && /UNIQUE constraint failed/i.test(error.message);
}
`;
}

function escapeComment(value: string): string {
  return value.replace(/\*\//g, "* /");
}
