#!/usr/bin/env node
/**
 * MPAS Bridge MCP Server
 * Generated by bridge-generator
 * Upstream: node ../examples/demo/tests/fixtures/adapter/github-mcp-server.mjs
 *
 * Tools: create_issue_demo, delete_branch_demo, merge_pull_request_demo
 *
 * This file is generated then checked in. Edit freely.
 *
 * Uses MCP 2026-07-28 Tasks when supported and the legacy MPAS wait-tool
 * compatibility surface for conventional MCP clients.
 */

import { readFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { StdioServerTransport } from "@modelcontextprotocol/server/stdio";
import {
  ActionPackageBuilder,
  ActionEndpointClient,
  CoordinationServiceClient,
  KeyManager,
  MemoryWorkflowStore,
  MpasProtocolServer,
  ProposerBridge,
} from "@oma3/mpas";
import type {
  BridgeUpstreamTool,
  MpasApplicationPlugin,
  ProposerConfig,
  WorkflowCoordinationService,
  WorkflowStore,
} from "@oma3/mpas";
import { SqliteWorkflowStore } from "./sqlite-workflow-store.js";

/**
 * The demo ships two applications — the dry-run mirror and the live demo — that
 * differ in tool names and applicationDid. One bridge binary serves both: the
 * tool surface is loaded from the path in `tools`. A real generated bridge bakes
 * its tools.json in beside the binary, since it fronts exactly one application.
 */
const DEFAULT_TOOLS_FILE = new URL("../../bridge-tools/github-live-demo-tools.json", import.meta.url);

function loadTools(path: string | undefined): BridgeUpstreamTool[] {
  const source = path ? pathToFileURL(path) : DEFAULT_TOOLS_FILE;
  return JSON.parse(readFileSync(source, "utf8")) as BridgeUpstreamTool[];
}

interface WorkflowConfig {
  /** SQLite database path. Omitted → in-memory store (no restart durability). */
  dbPath?: string;
  /** Minimum post-resolution retention disclosed to clients. Default 86400. */
  resultRetentionSeconds?: number;
  /** Background tick interval. Default 2000ms. */
  pollIntervalMs?: number;
  /** Client-facing tasks/get polling hint. Default 5000ms. */
  taskPollIntervalMs?: number;
  /** Compatibility wait-tool maximum. Default 300 seconds. */
  maxWaitTimeoutSeconds?: number;
  /** Deployment assigns maintainer notification outside the proposing client. */
  notificationAssignedElsewhere?: boolean;
  /**
   * Action and Coordination HTTP wait. Must stay below claimLeaseMs.
   * Default 30000.
   */
  submissionTimeoutMs?: number;
  /** Worker claim lease. Must exceed submissionTimeoutMs. Default 60000. */
  claimLeaseMs?: number;
}

interface BridgeConfig extends Omit<ProposerConfig, "approvalStrategy" | "approvalTimeoutMs"> {
  /** Path to the upstream tool surface this bridge exposes. */
  tools?: string;
  workflow?: WorkflowConfig;
}

interface CliConfig {
  mode?: "proposer" | "maintainer";
  plugin?: string;
  adapter?: {
    url?: string;
  };
  coordination?: {
    url?: string;
  };
  agent?: {
    did?: string;
    keyFile?: string;
  };
  target?: {
    applicationDid?: string;
  };
  applicationDid?: string;
  adapterUrl?: string;
  agentKey?: string;
  executionProfile?: {
    id: string;
    format: string;
  };
  tools?: string;
  workflow?: WorkflowConfig;
  defaultExpirationMinutes?: number;
  /** @deprecated Official MCP Tasks are always used. */
  approvalStrategy?: string;
  /** @deprecated See approvalStrategy. */
  approvalTimeoutMs?: number;
}

function log(level: "info" | "warn" | "error", msg: string, data?: object): void {
  const entry = { ts: new Date().toISOString(), level, msg, ...data };
  process.stderr.write(`[mpas-bridge] ${JSON.stringify(entry)}\n`);
}

export class GeneratedBridge {
  private readonly bridgePromise: Promise<ProposerBridge>;
  private readonly store: WorkflowStore;
  private readonly tools: BridgeUpstreamTool[];

  constructor(config: BridgeConfig) {
    this.tools = loadTools(config.tools);
    const plugin = loadPlugin(config.plugin);
    const keyManagerPromise = loadKeyManager(config.agentKey);
    const workflow = config.workflow ?? {};
    const submissionTimeoutMs = workflow.submissionTimeoutMs;
    const actionEndpoint = new ActionEndpointClient({
      url: config.adapterUrl,
      signer: keyManagerPromise,
      ...(submissionTimeoutMs !== undefined ? { timeoutMs: submissionTimeoutMs } : {}),
    });
    const coordinationService: WorkflowCoordinationService = config.coordinationUrl
      ? new CoordinationServiceClient({
          url: config.coordinationUrl,
          signer: keyManagerPromise,
          ...(submissionTimeoutMs !== undefined ? { timeoutMs: submissionTimeoutMs } : {}),
        })
      : unconfiguredCoordinationService();
    this.store = workflow.dbPath ? new SqliteWorkflowStore(workflow.dbPath) : new MemoryWorkflowStore();
    if (!workflow.dbPath) {
      log("warn", "memory_workflow_store", {
        note: "No workflow.dbPath configured; active Actions will not survive a bridge restart.",
      });
    }

    this.bridgePromise = keyManagerPromise.then((keyManager) => {
      const executionProfile = config.executionProfile ?? {
        id: plugin.executionProfile.id,
        format: plugin.executionProfile.format ?? "mcp.toolsCall",
      };
      const actionPackageBuilder = new ActionPackageBuilder({
        applicationDid: config.applicationDid,
        executionProfile,
        signer: keyManager,
        ...(config.defaultExpirationMinutes !== undefined
          ? { defaultExpirationMinutes: config.defaultExpirationMinutes }
          : {}),
      });
      return new ProposerBridge({
        tools: [...this.tools],
        buildActionPackage: (toolName, args) => actionPackageBuilder.buildFromToolCall(toolName, args),
        buildCoordinationReplacement: (priorPackage, verifierRequirements) =>
          actionPackageBuilder.buildCoordinationReplacement(priorPackage, verifierRequirements),
        store: this.store,
        actionEndpoint,
        coordinationService,
        proposerDid: keyManager.did,
        resultRetentionSeconds: workflow.resultRetentionSeconds ?? 86_400,
        ...(workflow.pollIntervalMs !== undefined ? { pollIntervalMs: workflow.pollIntervalMs } : {}),
        ...(workflow.taskPollIntervalMs !== undefined ? { taskPollIntervalMs: workflow.taskPollIntervalMs } : {}),
        ...(workflow.maxWaitTimeoutSeconds !== undefined ? { maxWaitTimeoutSeconds: workflow.maxWaitTimeoutSeconds } : {}),
        ...(workflow.notificationAssignedElsewhere !== undefined
          ? { notificationAssignedElsewhere: workflow.notificationAssignedElsewhere }
          : {}),
        ...(submissionTimeoutMs !== undefined ? { submissionTimeoutMs } : {}),
        ...(workflow.claimLeaseMs !== undefined ? { claimLeaseMs: workflow.claimLeaseMs } : {}),
      });
    });
  }

  getToolDefinitions(): BridgeUpstreamTool[] {
    return structuredClone(this.tools);
  }

  async handleToolCall(
    toolName: string,
    args: object,
  ): Promise<Awaited<ReturnType<ProposerBridge["handleToolCall"]>>> {
    log("info", "tool_call_received", { toolName });
    const bridge = await this.bridgePromise;
    return bridge.handleToolCall(toolName, args);
  }

  /** Startup reconciliation plus the background workflow loop. */
  async start(): Promise<void> {
    const bridge = await this.bridgePromise;
    await bridge.start();
    log("info", "bridge_started");
  }

  stop(): void {
    void this.bridgePromise.then((bridge) => {
      bridge.stop();
      this.store.close();
    });
  }

  async buildMcpServer(): Promise<MpasProtocolServer> {
    return new MpasProtocolServer({
      bridge: await this.bridgePromise,
      serverInfo: {
        name: "mpas-demo-github-server-mpas-bridge",
        version: "1.0.0",
      },
      onerror(error) {
        log("error", "mcp_protocol_error", { message: error.message });
      },
      onmode(mode, selector) {
        log("info", "mcp_protocol_mode_selected", { mode, selector });
      },
    });
  }
}

/**
 * Placeholder used when no coordinationUrl is configured. Approval-gated
 * Actions stay durably recorded in `created`/`awaitingApprovals` and are
 * retried by reconciliation; they cannot complete until coordination exists.
 */
function unconfiguredCoordinationService(): WorkflowCoordinationService {
  return {
    createApprovalWorkflow() {
      return Promise.reject(new Error("Coordination Service is not configured (coordination.url)."));
    },
    pollWork() {
      return Promise.resolve({
        version: "1" as const,
        type: "CoordinationPollResponse" as const,
        approvalRequests: [],
        actionUpdates: [],
      });
    },
    cancelAction() {
      return Promise.reject(new Error("Coordination Service is not configured (coordination.url)."));
    },
  };
}

export async function createBridgeFromConfig(configPath: string): Promise<GeneratedBridge> {
  const absoluteConfigPath = resolve(configPath);
  const configDir = dirname(absoluteConfigPath);
  const config = JSON.parse(await readFile(absoluteConfigPath, "utf8")) as CliConfig;
  return new GeneratedBridge(toBridgeConfig(config, configDir));
}

export async function runBridge(argv = process.argv.slice(2)): Promise<void> {
  const configPath = configPathFromArgs(argv);
  const bridge = await createBridgeFromConfig(configPath);
  const server = await bridge.buildMcpServer();
  const transport = new StdioServerTransport();

  await bridge.start();
  await server.connect(transport);
}

function toBridgeConfig(config: CliConfig, configDir: string): BridgeConfig {
  if (config.mode === "maintainer") {
    throw new Error("Maintainer/signer mode is not supported by this proposer bridge.");
  }
  if (!config.plugin) {
    throw new Error('Proposer bridge config requires "plugin".');
  }
  if (config.approvalStrategy !== undefined || config.approvalTimeoutMs !== undefined) {
    log("warn", "deprecated_config_ignored", {
      note: "approvalStrategy/approvalTimeoutMs are ignored: the bridge uses asynchronous Tasks or compatibility results.",
    });
  }
  const pluginPath = resolve(configDir, config.plugin);
  const plugin = loadPlugin(pluginPath);
  const adapterUrl = config.adapter?.url ?? config.adapterUrl;
  const agentKey = config.agent?.keyFile ?? config.agentKey;
  if (!adapterUrl) {
    throw new Error('Proposer bridge config requires "adapter.url".');
  }
  if (!agentKey) {
    throw new Error('Proposer bridge config requires "agent.keyFile".');
  }

  const toolsPath = config.tools ? resolve(configDir, config.tools) : undefined;
  const workflow: WorkflowConfig = { ...config.workflow };
  if (workflow.dbPath) {
    workflow.dbPath = resolve(configDir, workflow.dbPath);
  }

  return {
    plugin: pluginPath,
    applicationDid: (config.target?.applicationDid ?? config.applicationDid ?? plugin.applicationDid) as BridgeConfig["applicationDid"],
    adapterUrl,
    agentKey: resolve(configDir, agentKey),
    coordinationUrl: config.coordination?.url,
    executionProfile: (config.executionProfile ?? {
      id: plugin.executionProfile.id,
      format: plugin.executionProfile.format ?? "mcp.toolsCall",
    }) as BridgeConfig["executionProfile"],
    defaultExpirationMinutes: config.defaultExpirationMinutes,
    ...(toolsPath !== undefined ? { tools: toolsPath } : {}),
    workflow,
  };
}

function loadPlugin(plugin: BridgeConfig["plugin"]): MpasApplicationPlugin {
  if (typeof plugin === "string") {
    return JSON.parse(readFileSync(plugin, "utf8")) as MpasApplicationPlugin;
  }

  return plugin;
}

function loadKeyManager(agentKey: BridgeConfig["agentKey"]): Promise<KeyManager> {
  if (typeof agentKey === "string") {
    return KeyManager.fromFile(agentKey);
  }

  return Promise.resolve(KeyManager.fromJwk(agentKey));
}

function configPathFromArgs(argv: string[]): string {
  const configIndex = argv.indexOf("--config");
  const configPath = configIndex >= 0 ? argv[configIndex + 1] : undefined;
  if (!configPath) {
    throw new Error("Usage: mpas-bridge --config <path>");
  }

  return configPath;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await runBridge();
}
